server:
  port: 8088
  serlet:
    context-path: /springboot

management:
  server:
    port: 54001
  health:
    mail:
      enabled: false

info:
  app:
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"
    spring-boot-version: "@project.parent.version@"
#
#spring:
#  profiles:
#    active: prod
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/chris_wang?useUnicode=true&characterEncoding=gbk&characterSetResults=gbk&useSSL=false
#    username: root
#    password: wch1132
#
#  jpa:
#    hibernate:
#      ddl-autp:
#    show-sql: true

