server:
  port: 8080
  context-path: /springboot

management:
  port: 54001
  health:
    mail:
      enabled: false

endpoints:
  health:
    sensitive: false

info:
  app:
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"
    spring-boot-version: "@project.parent.version@"

girlBean:
  name: chris
  age: 25

spring:
  profiles:
    active: prod
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chris_wang?useUnicode=true&characterEncoding=gbk&characterSetResults=gbk&useSSL=false
    username: root
    password: wch1132

  jpa:
    hibernate:
      ddl-autp:
    show-sql: true

